# Generated by Django 3.0.7 on 2020-08-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dosage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchedaadhar', models.CharField(max_length=50, unique=True)),
                ('dosage_details', models.CharField(max_length=300)),
                ('visit_status', models.BooleanField(default=False)),
                ('dosage_date', models.DateField(blank=True, default='1990-09-09', null=True)),
                ('phone_no', models.CharField(default='', max_length=13)),
                ('loc', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('height_cm', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('camp_loc', models.CharField(default='', max_length=100)),
                ('aadhar1', models.CharField(max_length=4)),
                ('aadhar2', models.CharField(max_length=4)),
                ('aadhar3', models.CharField(max_length=4)),
                ('fullaadhar', models.CharField(default='', max_length=12, unique=True)),
                ('phone', models.CharField(default='', max_length=13)),
                ('imagepath', models.CharField(default='', max_length=100)),
                ('verstat', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
