# Generated by Django 3.0.7 on 2020-08-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('histaadhar', models.CharField(max_length=50, unique=True)),
                ('history1', models.CharField(max_length=300)),
                ('history_date1', models.DateField(blank=True, default='1990-09-09', null=True)),
                ('history2', models.CharField(max_length=300)),
                ('history_date2', models.DateField(blank=True, default='1990-09-09', null=True)),
                ('history3', models.CharField(max_length=300)),
                ('history_date3', models.DateField(blank=True, default='1990-09-09', null=True)),
                ('visit_count', models.CharField(default='', max_length=1)),
            ],
        ),
    ]
