# Generated by Django 3.0.7 on 2020-08-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20200801_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosage',
            name='height_cm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dosage',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='history_date1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='history_date2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='history_date3',
            field=models.DateField(blank=True, null=True),
        ),
    ]
