# Generated by Django 3.0.8 on 2020-08-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20200801_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='checkup',
            field=models.BooleanField(default=False),
        ),
    ]
