# Generated by Django 3.0.8 on 2020-08-02 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_register_checkup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='checkup',
            new_name='Clinical',
        ),
    ]
