# Generated by Django 3.0.8 on 2020-08-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20200802_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='Clinical',
        ),
        migrations.AddField(
            model_name='dosage',
            name='Diagnosis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='history',
            name='Diagnosis1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='history',
            name='Diagnosis2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='history',
            name='Diagnosis3',
            field=models.BooleanField(default=False),
        ),
    ]
