# Generated by Django 3.0.8 on 2020-08-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20200802_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='Diagnosis1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='history',
            name='Diagnosis2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='history',
            name='Diagnosis3',
            field=models.CharField(max_length=50),
        ),
    ]
