# Generated by Django 3.0.8 on 2020-08-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20200802_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='lang_pref',
            field=models.CharField(default='English', max_length=20),
        ),
    ]
