# Generated by Django 3.0.8 on 2020-08-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmail',
            name='account',
            field=models.BooleanField(default=False),
        ),
    ]
